################################
# ExperienceVanish v${project.version}
# Insider Build for MinecraftExperience Network | Kingdoms
#
# By tommaso.benatti#0001 : Sodio#2005
#
# Config updated at the version: 0.1
#
# All rights reserved | 2021 MinecraftExperience™
################################

#################################################
#
#   ______                      _                  __      __         _     _
#  |  ____|                    (_)                 \ \    / /        (_)   | |
#  | |__  __  ___ __   ___ _ __ _  ___ _ __   ___ __\ \  / /_ _ _ __  _ ___| |__
#  |  __| \ \/ / '_ \ / _ \ '__| |/ _ \ '_ \ / __/ _ \ \/ / _` | '_ \| / __| '_ \
#  | |____ >  <| |_) |  __/ |  | |  __/ | | | (_|  __/\  / (_| | | | | \__ \ | | |
#  |______/_/\_\ .__/ \___|_|  |_|\___|_| |_|\___\___| \/ \__,_|_| |_|_|___/_| |_|
#              | |
#              |_|
#
################################

# >>> Permissions <<<
#
# experiencevanish.help
#
################################
